# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "no_intra_emphasis", "strikethrough", "superscript", "tables", "with_toc_data"]
pygments: true

# Permalinks
permalink: pretty

# GitHub project page
baseurl: /blog

# Setup
title: PMML Cookbook
tagline: Practical Solutions to Predictive Analytics Problems
url: http://openscoring.io

excerpt_separator: <!-- more -->

paginate: 10

pages_list:
  About: /about/
  Feed: /atom.xml
